name: Android CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        #Check for gradlew
      - name: Look for gradlew
        run: sudo find / -type f -name "gradlew"

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
