name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 1.11.0.15

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk